"""
preprocess.py
generates vocabulary.py
requires: simpleneighbors (pip install simpleneighbors)
"""

import json
import random
from collections import defaultdict, Counter

try:
    from simpleneighbors import SimpleNeighbors
except ImportError:
    print("install simpleneighbors first: pip install simpleneighbors")
    exit(1)

# load corpus jsonl
JSONL_FILE = "semantic-categories-2026-04-10.jsonl"

lines = open(JSONL_FILE).readlines()
cats = defaultdict(list)
for item in lines:
    obj = json.loads(item)
    if len(obj['label']) > 0:
        cats[obj['text'].lower()].extend(obj['label'])

cats_counted = {word: Counter(tags) for word, tags in cats.items()}

# builds vectorizer
unique_features = set()
for val in cats.values():
    unique_features.update(val)
cols = sorted(list(unique_features))
name2idx = {name: i for i, name in enumerate(cols)}

cats_vectorized = {}
for word, counts in cats_counted.items():
    cats_vectorized[word] = [counts.get(feat, 0) for feat in cols]

lookup = SimpleNeighbors(len(cols), metric="angular")
for word, vec in cats_vectorized.items():
    lookup.add_one(word, vec)
lookup.build()

# helper functions
def make_vector(**kwargs):
    vec = [0] * len(cols)
    for k, v in kwargs.items():
        if k in name2idx:
            vec[name2idx[k]] = v
    return vec

def has_forbidden(word, forbidden):
    tags = set(cats_counted.get(word, Counter()).keys())
    return bool(tags & forbidden)

def get_neighbors(target_vec, n=40, forbidden=None):
    candidates = lookup.nearest(target_vec, n=n)
    if forbidden:
        candidates = [w for w in candidates if not has_forbidden(w, forbidden)]
    return candidates[:20]  # keep top 20 after filtering

forbidden = {"cold", "sharp", "academic"}

# defines semantic neighborhoods for each slot × temperature
# these map to the poem template:
#   a computer of {material}
#        bound by {structure}
#             powered by {power}
#                   with {interface}
#                        resting among {location}
#                             inhabited by {inhabitant}
#                                  and it offers {promise}

# COOL temperature — organic+tangible pull, moderate emotive
cool_pools = {
    "material":   get_neighbors(make_vector(organic=2, tangible=2), forbidden=forbidden),
    "structure":  get_neighbors(make_vector(round=2, tangible=1), forbidden=forbidden),
    "power":      get_neighbors(make_vector(organic=2, tangible=1), forbidden=forbidden),
    "interface":  get_neighbors(make_vector(tangible=2), forbidden=forbidden),
    "location":   get_neighbors(make_vector(round=2, organic=1), forbidden=forbidden),
    "inhabitant": get_neighbors(make_vector(emotive=2, organic=1), forbidden=forbidden),
    "promise":    get_neighbors(make_vector(emotive=2, youthful=1), forbidden=forbidden),
}

# NEUTRAL temperature — warm+organic pull, balanced
neutral_pools = {
    "material":   get_neighbors(make_vector(organic=2, tangible=2, warm=1), forbidden=forbidden),
    "structure":  get_neighbors(make_vector(round=2, warm=1), forbidden=forbidden),
    "power":      get_neighbors(make_vector(warm=3, organic=1), forbidden=forbidden),
    "interface":  get_neighbors(make_vector(tangible=2, warm=1), forbidden=forbidden),
    "location":   get_neighbors(make_vector(warm=2, round=2), forbidden=forbidden),
    "inhabitant": get_neighbors(make_vector(emotive=3, warm=1), forbidden=forbidden),
    "promise":    get_neighbors(make_vector(emotive=2, youthful=1, warm=1), forbidden=forbidden),
}

# WARM temperature — deep emotive+youthful+organic pull
warm_pools = {
    "material":   get_neighbors(make_vector(organic=3, warm=2, youthful=1), forbidden=forbidden),
    "structure":  get_neighbors(make_vector(round=3, warm=2, organic=1), forbidden=forbidden),
    "power":      get_neighbors(make_vector(warm=3, emotive=2, organic=1), forbidden=forbidden),
    "interface":  get_neighbors(make_vector(tangible=2, warm=2, emotive=1), forbidden=forbidden),
    "location":   get_neighbors(make_vector(warm=3, round=2, emotive=1), forbidden=forbidden),
    "inhabitant": get_neighbors(make_vector(emotive=3, warm=2, youthful=1), forbidden=forbidden),
    "promise":    get_neighbors(make_vector(emotive=3, youthful=2, warm=1), forbidden=forbidden),
}

# write vocabulary.py
with open("vocabulary.py", "w") as f:
    f.write('# vocabulary.py\n')
    f.write('# auto-generated by preprocess.py — do not edit by hand\n')
    f.write('# drop this on CIRCUITPY alongside code.py\n\n')
    
    for temp_name, pools in [("COOL", cool_pools), ("NEUTRAL", neutral_pools), ("WARM", warm_pools)]:
        for slot, words in pools.items():
            varname = f"{temp_name}_{slot.upper()}"
            f.write(f"{varname} = {words}\n")
        f.write("\n")

print("wrote vocabulary.py")
print("\nspot check — sample WARM poem:")
for slot in ["material", "structure", "power", "interface", "location", "inhabitant", "promise"]:
    w = random.choice(warm_pools[slot]) if warm_pools[slot] else "???"
    print(f"  {slot}: {w}")
